notes_app/core/urls.py
from django.urls import path
from .views import Home, About, Terms

app_name = 'core'
urlpatterns = [
  path('', Home.as_view(), name='home'),
  path('about/', About.as_view(), name='about'),
  path('terms/', Terms.as_view(), name='terms'),
]

notes_app/notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'
urlpatterns = [
  path('', views.NoteList.as_view(), name='note-list'),
  path('<int:pk>/', views.NoteDetail.as_view(), name='note-detail'),
  path('create/', views.NoteCreate.as_view(), name='note-create'),
  path('update/<int:pk>/', views.NoteUpdate.as_view(), name='note-update'),
  path('delete/<int:pk>/', views.NoteDelete.as_view(), name='note-delete'),
]

notes_app/notes_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls', namespace='registration')),
    path('notes/', include('notes.urls', namespace='notes')),
    path('admin/', admin.site.urls),
]

notes_app/registration/urls.py
from django.urls import path
from . import views

app_name = 'registration'
urlpatterns = [
  path('signup/', views.Signup.as_view(), name='signup'),
  path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
]

notes_app/core/models.py
from django.db import models

# Create your models here.

notes_app/notes/models.py
from django.db import models
from django.contrib.auth.models import User

class Note(models.Model):
  title = models.CharField(max_length=150)
  description = models.TextField()
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  craeted_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  
  def __str__(self):
    return self.description

notes_app/notes/forms.py
from django import forms
from .models import Note

class NoteForm(forms.ModelForm):
  class Meta:
    model = Note
    fields = ['title', 'description',]

notes_app/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class Home(TemplateView):
  template_name = 'core/home.html'

class About(TemplateView):
  template_name = 'core/about.html'

class Terms(TemplateView):
  template_name = 'core/terms.html'

notes_app/notes/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views import generic
from .models import Note
from .forms import NoteForm

class NoteList(generic.ListView):
  model = Note

  def get_queryset(self):
    user = User.objects.get(username=self.request.user.username)
    return Note.objects.filter(user=user).order_by('-updated_at')

class NoteDetail(generic.DetailView):
  model = Note

class NoteCreate(generic.CreateView):
  model = Note
  form_class = NoteForm
  success_url = reverse_lazy('notes:note-list')

  def form_valid(self, form):
    self.object = form.save(commit=False)
    self.object.user = self.request.user
    self.object.save()
    return super().form_valid(form)

class NoteUpdate(generic.UpdateView):
  model = Note
  form_class = NoteForm
  success_url = reverse_lazy('notes:note-list')

class NoteDelete(generic.DeleteView):
  model = Note
  form_class = NoteForm
  success_url = reverse_lazy('notes:note-list')

notes_app/templates/notes/note_confirm_delete.html
Are you sure you want to delete {{ note.name }}?

<form method="post">
  {% csrf_token %}
  <button type="submit">Yeah whatever</button>
  <a href="{% url 'notes:note-list' %}">Nevermind</a>
</form>

notes_app/templates/notes/note_detail.html
<a href="{% url 'notes:note-list' %}">Back to list</a>
<br>
<br>
Id: {{ note.id }}
<br />
Title: {{ note.title }}
<br />
Description: {{ note.description }}

notes_app/templates/notes/note_form.html
Save note

<form method="POST">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save</button>
</form>

notes_app/templates/notes/note_list.html
<a href="{% url 'notes:note-create' %}">Create</a>
<br />

{% if note_list %}
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for note in note_list %}
        <tr>
          <td>
            <a href="{% url 'notes:note-detail' note.id %}">{{ note.title }}</a>
          </td>
          <td>
            <a href="{% url 'notes:note-update' note.id %}">Update</a>
          </td>
          <td>
            <a href="{% url 'notes:note-delete' note.id %}">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  Nothing to show
{% endif %}