marvel_heroes/core/urls.py
from django.urls import path
from .views import Home, About

app_name = 'core'
urlpatterns = [
  path('', Home.as_view(), name='home'),
  path('about/', About.as_view(), name='about'),
]

marvel_heroes/heroes/urls.py
from django.urls import path
from . import views

app_name = 'heroes'
urlpatterns = [
  path('', views.HeroList.as_view(), name='hero-list'),
  path('<int:pk>/', views.HeroDetail.as_view(), name='hero-detail'),
  path('create/', views.HeroCreate.as_view(), name='hero-create'),
  path('update/<int:pk>/', views.HeroUpdate.as_view(), name='hero-update'),
  path('delete/<int:pk>/', views.HeroDelete.as_view(), name='hero-delete'),
]

marvel_heroes/marvel_heroes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('heroes/', include('heroes.urls', namespace='heroes')),
    path('villains/', include('villains.urls', namespace='villains')),
    path('admin/', admin.site.urls),
]

marvel_heroes/villains/urls.py
from django.urls import path
from . import views

app_name = 'villains'
urlpatterns = [
  path('', views.VillainList.as_view(), name='villain-list'),
  path('<int:pk>/', views.VillainDetail.as_view(), name='villain-detail'),
  path('create/', views.VillainCreate.as_view(), name='villain-create'),
  path('update/<int:pk>/', views.VillainUpdate.as_view(), name='villain-update'),
  path('delete/<int:pk>/', views.VillainDelete.as_view(), name='villain-delete'),
]

marvel_heroes/core/models.py
from django.db import models

# Create your models here.

marvel_heroes/heroes/models.py
from django.db import models

class Hero(models.Model):
  name = models.CharField(max_length=250)
  superpower = models.CharField(max_length=150)
  secret_identity = models.CharField(max_length=250)
  craeted_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
  updated_at = models.DateTimeField(auto_now=True)

  class Meta:
    verbose_name_plural = 'Heroes'

marvel_heroes/villains/models.py
from django.db import models

class Villain(models.Model):
  name = models.CharField(max_length=250)
  superpower = models.CharField(max_length=150)
  secret_identity = models.CharField(max_length=250)
  craeted_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
  updated_at = models.DateTimeField(auto_now=True)
  

marvel_heroes/heroes/forms.py
from django import forms
from .models import Hero

class HeroForm(forms.ModelForm):
  class Meta:
    model = Hero
    fields = ['name', 'superpower', 'secret_identity',]

marvel_heroes/villains/forms.py
from django import forms
from .models import Villain

class VillainForm(forms.ModelForm):
  class Meta:
    model = Villain
    fields = ['name', 'superpower', 'secret_identity',]

marvel_heroes/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class Home(TemplateView):
  template_name = 'core/home.html'

class About(TemplateView):
  template_name = 'core/about.html'

marvel_heroes/heroes/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .models import Hero
from .forms import HeroForm

class HeroList(generic.ListView):
  model = Hero

class HeroDetail(generic.DetailView):
  model = Hero

class HeroCreate(generic.CreateView):
  model = Hero
  form_class = HeroForm
  success_url = reverse_lazy('heroes:hero-list')

class HeroUpdate(generic.UpdateView):
  model = Hero
  form_class = HeroForm
  success_url = reverse_lazy('heroes:hero-list')

class HeroDelete(generic.DeleteView):
  model = Hero
  form_class = HeroForm
  success_url = reverse_lazy('heroes:hero-list')

marvel_heroes/villains/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .models import Villain
from .forms import VillainForm

class VillainList(generic.ListView):
  model = Villain

class VillainDetail(generic.DetailView):
  model = Villain

class VillainCreate(generic.CreateView):
  model = Villain
  form_class = VillainForm
  success_url = reverse_lazy('villains:villain-list')

class VillainUpdate(generic.UpdateView):
  model = Villain
  form_class = VillainForm
  success_url = reverse_lazy('villains:villain-list')

class VillainDelete(generic.DeleteView):
  model = Villain
  form_class = VillainForm
  success_url = reverse_lazy('villains:villain-list')

marvel_heroes/templates/villains/villain_confirm_delete.html
Are you sure you want to delete {{ villain.name }}?

<form method="post">
  {% csrf_token %}
  <button type="submit">Yeah whatever</button>
  <a href="{% url 'villains:villain-list' %}">Nevermind</a>
</form>

marvel_heroes/templates/villains/villain_detail.html
<a href="{% url 'villains:villain-list' %}">Back to list</a>
<br>
<br>
Id: {{ villain.id }}
<br />
Name: {{ villain.name }}
<br />
Price: {{ villain.superpower }}
<br />
Price: {{ villain.secret_identity }}

marvel_heroes/templates/villains/villain_form.html
Save villain

<form method="POST">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save</button>
</form>

marvel_heroes/templates/villains/villain_list.html
<a href="{% url 'villains:villain-create' %}">Create</a>
<br />

{% if villain_list %}
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for villain in villain_list %}
        <tr>
          <td>
            <a href="{% url 'villains:villain-detail' villain.id %}">{{ villain.name }}</a>
          </td>
          <td>
            <a href="{% url 'villains:villain-update' villain.id %}">Update</a>
          </td>
          <td>
            <a href="{% url 'villains:villain-delete' villain.id %}">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  Nothing to show
{% endif %}