academic_system/academic_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('students/', include('students.urls', namespace='students')),
    path('professors/', include('professors.urls', namespace='professors')),
    path('admin/', admin.site.urls),
]

academic_system/core/urls.py
from django.urls import path
from .views import Home, About

app_name = 'core'
urlpatterns = [
  path('', Home.as_view(), name='home'),
  path('about/', About.as_view(), name='about'),
]

academic_system/professors/urls.py
from django.urls import path
from . import views

app_name = 'professors'
urlpatterns = [
  path('', views.ProfessorList.as_view(), name='professor-list'),
  path('<int:pk>/', views.ProfessorDetail.as_view(), name='professor-detail'),
  path('create/', views.ProfessorCreate.as_view(), name='professor-create'),
  path('update/<int:pk>/', views.ProfessorUpdate.as_view(), name='professor-update'),
  path('delete/<int:pk>/', views.ProfessorDelete.as_view(), name='professor-delete'),
]

academic_system/students/urls.py
from django.urls import path
from . import views

app_name = 'students'
urlpatterns = [
  path('', views.StudentList.as_view(), name='student-list'),
  path('<int:pk>/', views.StudentDetail.as_view(), name='student-detail'),
  path('create/', views.StudentCreate.as_view(), name='student-create'),
  path('update/<int:pk>/', views.StudentUpdate.as_view(), name='student-update'),
  path('delete/<int:pk>/', views.StudentDelete.as_view(), name='student-delete'),
]

academic_system/core/models.py
from django.db import models

# Create your models here.

academic_system/professors/models.py
from django.db import models

class Professor(models.Model):
  name = models.CharField(max_length=250)
  

academic_system/students/models.py
from django.db import models

class Student(models.Model):
  name = models.CharField(max_length=250)
  

academic_system/professors/forms.py
from django import forms
from .models import Professor

class ProfessorForm(forms.ModelForm):
  class Meta:
    model = Professor
    fields = ['name',]

academic_system/students/forms.py
from django import forms
from .models import Student

class StudentForm(forms.ModelForm):
  class Meta:
    model = Student
    fields = ['name',]

academic_system/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class Home(TemplateView):
  template_name = 'core/home.html'

class About(TemplateView):
  template_name = 'core/about.html'

academic_system/professors/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .models import Professor
from .forms import ProfessorForm

class ProfessorList(generic.ListView):
  model = Professor

class ProfessorDetail(generic.DetailView):
  model = Professor

class ProfessorCreate(generic.CreateView):
  model = Professor
  form_class = ProfessorForm
  success_url = reverse_lazy('professors:professor-list')

class ProfessorUpdate(generic.UpdateView):
  model = Professor
  form_class = ProfessorForm
  success_url = reverse_lazy('professors:professor-list')

class ProfessorDelete(generic.DeleteView):
  model = Professor
  form_class = ProfessorForm
  success_url = reverse_lazy('professors:professor-list')

academic_system/students/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .models import Student
from .forms import StudentForm

class StudentList(generic.ListView):
  model = Student

class StudentDetail(generic.DetailView):
  model = Student

class StudentCreate(generic.CreateView):
  model = Student
  form_class = StudentForm
  success_url = reverse_lazy('students:student-list')

class StudentUpdate(generic.UpdateView):
  model = Student
  form_class = StudentForm
  success_url = reverse_lazy('students:student-list')

class StudentDelete(generic.DeleteView):
  model = Student
  form_class = StudentForm
  success_url = reverse_lazy('students:student-list')

academic_system/templates/core/about.html
We are...

{% lorem 3 p %}

academic_system/templates/core/home.html
Welcome to students system

<a href="{% url 'students:student-list' %}">Student list</a>
<br />
<a href="{% url 'professors:professor-list' %}">Professor list</a>

academic_system/templates/students/student_confirm_delete.html
Are you sure you want to delete {{ student.name }}?

<form method="post">
  {% csrf_token %}
  <button type="submit">Yeah whatever</button>
  <a href="{% url 'students:student-list' %}">Nevermind</a>
</form>

academic_system/templates/students/student_detail.html
Id: {{ student.id }}
<br />
Name: {{ student.name }}

<a href="{% url 'students:student-update' student.id %}">Update</a>
<br />
<a href="{% url 'students:student-delete' student.id %}">Delete</a>

academic_system/templates/students/student_form.html
Create student

<form method="POST">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save</button>
</form>

academic_system/templates/students/student_list.html
<a href="{% url 'students:student-create' %}">Create</a>
<br />

<ul>
  {% for student in student_list %}
    <li>
      <a href="{% url 'students:student-detail' student.id %}">{{ student.name }}</a>
    </li>
  {% empty %}
    Nothing to show
  {% endfor %}
</ul>