arduino_store/arduino_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('employees/', include('employees.urls', namespace='employees')),
    path('products/', include('products.urls', namespace='products')),
    path('admin/', admin.site.urls),
]

arduino_store/core/urls.py
from django.urls import path
from .views import Home, About

app_name = 'core'
urlpatterns = [
  path('', Home.as_view(), name='home'),
  path('about/', About.as_view(), name='about'),
]

arduino_store/employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'
urlpatterns = [
  path('', views.EmployeeList.as_view(), name='employee-list'),
  path('<int:pk>/', views.EmployeeDetail.as_view(), name='employee-detail'),
  path('create/', views.EmployeeCreate.as_view(), name='employee-create'),
  path('update/<int:pk>/', views.EmployeeUpdate.as_view(), name='employee-update'),
  path('delete/<int:pk>/', views.EmployeeDelete.as_view(), name='employee-delete'),
]

arduino_store/products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
  path('', views.ProductList.as_view(), name='product-list'),
  path('<int:pk>/', views.ProductDetail.as_view(), name='product-detail'),
  path('create/', views.ProductCreate.as_view(), name='product-create'),
  path('update/<int:pk>/', views.ProductUpdate.as_view(), name='product-update'),
  path('delete/<int:pk>/', views.ProductDelete.as_view(), name='product-delete'),
]

arduino_store/core/models.py
from django.db import models

# Create your models here.

arduino_store/employees/models.py
from django.db import models

class Employee(models.Model):
  name = models.CharField(max_length=250)
  position = models.CharField(max_length=100)
  salary = models.DecimalField(max_digits=8, decimal_places=2)

arduino_store/products/models.py
from django.db import models

class Product(models.Model):
  name = models.CharField(max_length=250)
  price = models.DecimalField(max_digits=7, decimal_places=2)
  

arduino_store/employees/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
  class Meta:
    model = Employee
    fields = ['name', 'position', 'salary',]

arduino_store/products/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
  class Meta:
    model = Product
    fields = ['name', 'price']

arduino_store/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class Home(TemplateView):
  template_name = 'core/home.html'

class About(TemplateView):
  template_name = 'core/about.html'

arduino_store/employees/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .models import Employee
from .forms import EmployeeForm

class EmployeeList(generic.ListView):
  model = Employee

class EmployeeDetail(generic.DetailView):
  model = Employee

class EmployeeCreate(generic.CreateView):
  model = Employee
  form_class = EmployeeForm
  success_url = reverse_lazy('employees:employee-list')

class EmployeeUpdate(generic.UpdateView):
  model = Employee
  form_class = EmployeeForm
  success_url = reverse_lazy('employees:employee-list')

class EmployeeDelete(generic.DeleteView):
  model = Employee
  form_class = EmployeeForm
  success_url = reverse_lazy('employees:employee-list')

arduino_store/products/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .models import Product
from .forms import ProductForm

class ProductList(generic.ListView):
  model = Product

class ProductDetail(generic.DetailView):
  model = Product

class ProductCreate(generic.CreateView):
  model = Product
  form_class = ProductForm
  success_url = reverse_lazy('products:product-list')

class ProductUpdate(generic.UpdateView):
  model = Product
  form_class = ProductForm
  success_url = reverse_lazy('products:product-list')

class ProductDelete(generic.DeleteView):
  model = Product
  form_class = ProductForm
  success_url = reverse_lazy('products:product-list')

arduino_store/templates/core/about.html
We are...

{% lorem 3 p %}

arduino_store/templates/core/home.html
Welcome to Arduino store

arduino_store/templates/employees/employee_confirm_delete.html
Are you sure you want to delete {{ employee.name }}?

<form method="post">
  {% csrf_token %}
  <button type="submit">Yeah whatever</button>
  <a href="{% url 'employees:employee-list' %}">Nevermind</a>
</form>

arduino_store/templates/employees/employee_detail.html
Id: {{ employee.id }}
<br />
Name: {{ employee.name }}
<br />
Position: {{ employee.position }}
<br />
Salary: {{ employee.salary }}
<br />

<a href="{% url 'employees:employee-update' employee.id %}">Update</a>
<br />
<a href="{% url 'employees:employee-delete' employee.id %}">Delete</a>

arduino_store/templates/employees/employee_form.html
Save employee

<form method="POST">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save</button>
</form>

arduino_store/templates/employees/employee_list.html
<a href="{% url 'employees:employee-create' %}">Create</a>
<br />

<ul>
  {% for employee in employee_list %}
    <li>
      <a href="{% url 'employees:employee-detail' employee.id %}">{{ employee.name }}</a>
    </li>
  {% empty %}
    Nothing to show
  {% endfor %}
</ul>